version: '3.8'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
  authservice:
    hostname: authservice
    build:
      dockerfile: AuthService.Dockerfile
    ports:
      - "4002:4002"
    environment:
      - ASPNETCORE_URLS=http://+:4002
      - RabbitMQConnectionString=amqp://username:password@rabbitmq:5672
  tweetservice:
    hostname: tweetservice
    build:
      dockerfile: TweetService.Dockerfile
    ports:
      - "4003:4003"
    environment:
      - ASPNETCORE_URLS=http://+:4003
      - RabbitMQConnectionString=amqp://username:password@rabbitmq:5672
  notificationservice:
    hostname: NotificationService
    build:
      dockerfile: NotificationService.Dockerfile
    ports:
      - "4004:4004"
    environment:
      - ASPNETCORE_URLS=http://+:4004
      - RabbitMQConnectionString=amqp://username:password@rabbitmq:5672