name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - Backend/**
    
jobs:
  build_TweetService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./TweetService.Dockerfile --tag ghcr.io/joepvand/kwetter/tweetservice:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        cd TweetService/TweetService.Api
        docker push ghcr.io/joepvand/kwetter/tweetservice:latest
  build_ProfileService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./ProfileService.Dockerfile --tag ghcr.io/joepvand/kwetter/profileservice:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        cd ProfileService
        docker push ghcr.io/joepvand/kwetter/profileservice:latest
  build_AuthService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./AuthService.Dockerfile --tag ghcr.io/joepvand/kwetter/authservice:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        docker push ghcr.io/joepvand/kwetter/authservice:latest
  build_NotificationService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./NotificationService.Dockerfile --tag ghcr.io/joepvand/kwetter/notificationservice:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        docker push ghcr.io/joepvand/kwetter/notificationservice:latest
  build_Gateway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./Gateway.Dockerfile --tag ghcr.io/joepvand/kwetter/gateway:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        docker push ghcr.io/joepvand/kwetter/gateway:latest
  build_ReportService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./ReportService.Dockerfile --tag ghcr.io/joepvand/kwetter/reportservice:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        docker push ghcr.io/joepvand/kwetter/reportservice:latest
  build_CommentService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd Backend
        docker build . --file ./CommentService.Dockerfile --tag ghcr.io/joepvand/kwetter/commentservice:latest
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}
        docker push ghcr.io/joepvand/kwetter/commentservice:latest
