name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_TweetService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Move directory
      run: cd TweetService/TweetService.Api
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -warnaserror
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build_ProfileService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Move directory
      run: cd ProfileService/ProfileService.Api
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -warnaserror
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build_AuthService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Move directory
      run: cd Auth/AuthService.Api
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -warnaserror
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build_NotificationService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Move directory
      run: cd NotificationService/NotificationService.Api
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -warnaserror
    - name: Test
      run: dotnet test --no-build --verbosity normal
